### PR TITLE
Update Packages-Desktop

### PR DESCRIPTION
**Pull request by Chrysostomus**
Change browser and move more packages to >extra

### CODE REVIEW

**Comment by Chrysostomus** [comment]
Also added set slick-greeter for gnome edition. The current configuration files for lightdm could not have worked anyway (wrong greeter set)

**Comment by Ste74** [comment]
@udeved , @philmmanjaro @Kirek 
can add a gnome-next folder ? Or you prefer to build in my github repo and merge when ready with gnome profile ? At the moment don't wont mix the devel ( gnome-next )  with the current ...

**Comment by Chrysostomus** [comment]
I would just update the profile, because manjaro-architect uses the iso-profile for installation, and right now the profile is outdated.

**Comment by Chrysostomus** [comment]
If you add gnome-next, it makes for an extra option in manjaro-architect.

**Comment by Ste74** [comment]
Ok , no other profiles are needed , all change go to iso profiles with manjaro-gnome-settings-dev 😄 at the end this -dev pkg merge into the normal 😉

**Pull request merged**
