### PR TITLE
Update Packages-Desktop

### PR DESCRIPTION
**Pull request by Chrysostomus**
Add gdm3setup for login screen customization.

### CODE REVIEW

**Comment by Ste74** [comment]
I have suspected you want use this .. :D .. have you try it ? I have add this in the past and updated the pkgs but i have notice this not work after 3.20.x...

**Comment by Chrysostomus** [comment]
It has worked for me. I have tried it

**Comment by Ste74** [comment]
Ok .. good to know :)

**Comment by Chrysostomus** [comment]
No idea what it uses to alter the settings though... But it seems to work.

**Comment by Ste74** [comment]
When go to home or at last tomorrow i do it to build the new iso ;)

**Pull request merged**
