### PR TITLE
add webdad profile

### PR DESCRIPTION
**Pull request by codesardine**

### CODE REVIEW

**Comment by Ste74** [comment]
@philmmanjaro , @codesardine have you checked ? :p Not understand what you have in PR :p

**Comment by codesardine** [comment]
@Ste74  @philmmanjaro ops sorry thats wrong should not be a submodule

**Comment by Ste74** [comment]
Don't worry @codesardine lol

**Comment by codesardine** [comment]
ok if thats not working files are here https://github.com/codesardine/manjaro-webdad-iso-profile

**Pull request merged**
