### PR TITLE
Comply with the new manjaro-lxde-settings changes

### PR DESCRIPTION
**Pull request by ThanosApostolou**

### CODE REVIEW

**Comment by oberon2007** [comment]
Just pushed the updated settings package.
I suggest you build another test-ISO against unstable branch with the latest changes and when you've uploaded, just add me as a collaborator at your project, then I can move the files to "manjarotest-community" account.
Then you can make another forum announcement for broader testing.
Does that sound like a good plan to you?

**Comment by ThanosApostolou** [comment]
Ok nice, sounds perfect! Since all the important changes are finished, I will name it "alpha1" in order to inspire more testers. Just one thing, I do see the new `manjaro-lxde-logout-banner` but I don't see the dependencies in `manjaro-lxde-settings` (I'm on https://mirror.netzspielplatz.de/manjaro/packages mirror which is always updated).

**Comment by oberon2007** [comment]
beh, you are right. I forgot to pull the changes first, sorry!

**Comment by oberon2007** [comment]
**manjaro-lxde-settings-20170404-2** 👍

**Comment by ThanosApostolou** [comment]
I'm building right now alpha1 which will be uploaded right afterwards (takes about 8 hours on my connection). I created a post about default software to be included: https://forum.manjaro.org/t/default-software-polls-for-manjaro-lxde-edition-vote/21056?u=thanos_apostolou. If there are changes I should do an alpha2 release in a few days. Else, there will be only minor fixes and we will be ready to push them into testing and go for beta1 without alpha2. When alpha1 is finished, after you move the files to manjarotest-community account I will also create a new post asking for more testers (I don't have access to the Announcements section so I will do it under Development section again unless someone grants me access).

**Comment by ThanosApostolou** [comment]
@oberon2007 Ok the upload is finished. I added you as admin to my sourceforge project, https://sourceforge.net/projects/thanos-manjaro-lxde/files/manjaro-lxde-17.0.1-alpha1/. If you can move it to the manjarotest-community sourceforge account.

**Comment by oberon2007** [comment]
done :)
https://sourceforge.net/projects/manjarotest-community/files/lxde/manjaro-lxde-17.0.1-alpha1/

**Pull request merged**
