### PR TITLE
add architect-profile

### PR DESCRIPTION
**Pull request by oberon2007**
minimalistic CLI profile with pkg **manjaro-architect-launcher** to install the latest version of the CLI-installer **manjaro-architect** in the live environment.
Like that the ISO practically will never need to be updated.
Current state of the installer can be followed on [@Chrysostomus ' repo](https://github.com/Chrysostomus/manjaro-architect)
and on the [testing thread](https://forum.manjaro.org/t/experimental-manjaro-architect-test-iso/17661) of the forum.

### CODE REVIEW

**Comment by Huluti** [comment]
The logo isn't a square... :)

**Comment by oberon2007** [comment]
Yes, it is in the console! :rofl:

**Comment by oberon2007** [comment]
:angel:

**Comment by oberon2007** [comment]
better?
```
                 -/+:.         
                :++++.         
               /+++/.          
       .:-::- .+/:-\`\`.::-     
    .:/++++++/::::/++++++/:\`   
  .:///////////////////////:\`  
  ////////////////////////\`    
 -+++++++++++++++++++++++\`     
 /++++++++++++++++++++++/      
 /sssssssssssssssssssssss.     
 :ssssssssssssssssssssssss-    
  osssssssssssssssssssssssso/\` 
  \`syyyyyyyyyyyyyyyyyyyyyyyy+\` 
   \`ossssssssssssssssssssss/
     :ooooooooooooooooooo+.
      \`:+oo+/:-..-:/+o+/- 
```

**Comment by Huluti** [comment]
What a shame :O

**Comment by philmmanjaro** [comment]
Come on ...

```
                 __
            ,-~¨^  ^¨-,           _,
           /          / ;^-._...,¨/
          /          / /         /
         /          / /         /
        /          / /         /
       /,.-:''-,_ / /         /
       _,.-:--._ ^ ^:-._ __../
     /^         / /¨:.._¨__.;
    /          / /      ^  /
   /          / /         /
  /          / /         /
 /_,.--:^-._/ /         /
^            ^¨¨-.___.:^
```

**Pull request merged**
