### PR TITLE
Update

### PR DESCRIPTION
**Pull request by codesardine**
packages bellow need an update, thanks
manjaro-webdad-settings
webdad-theming
jade-dashboard

### CODE REVIEW

**Comment by codesardine** [comment]
Do I need to do changes in .xinitrc In dbus section? It seams to work with the defaults.

**Comment by Ste74** [comment]
Ops forgot this PR.. let me build your pkgs

**Comment by Ste74** [comment]
@codesardine please correct this
https://github.com/manjaro/packages-community/blob/master/webdad-theming-git/PKGBUILD
and submit PR on the repo community :smile:

**Comment by codesardine** [comment]
What needs to be corrected @Ste74?

**Pull request merged**
