### PR TITLE
Update webdad

### PR DESCRIPTION
**Pull request by codesardine**
Don't take this in just yet as i am waiting for webdad packages to get into unstable to test it @oberon2007

### CODE REVIEW

**Comment by codesardine** [comment]
This image is building and working just tested @oberon2007

**Comment by oberon2007** [comment]
Nice! Thank you! Will give it a spin tomorrow :smiley: exciting!

**Comment by oberon2007** [comment]
will build jak as soon as my kernels are finished here ... :wink:

**Comment by codesardine** [comment]
New version fixes download issues with office, Thanks

**Pull request merged**
