### PR TITLE
Elogind

### PR DESCRIPTION
**Pull request by udeved**

### CODE REVIEW

**Comment by oberon2007** [comment]
Wow! cool, thank you :)
In architect Packages-Live there's a missing newline at ``>openrc xf86-input-libinput-nosystemdxf86-input-mouse``
Also, since Budgie profile doesn't work with openrc afaik, could you please not add any openrc flags there, because architect installer will assume that the profile is ready for openrc...

**Comment by udeved** [comment]
There live packages are updated in unstable, we need to rebuild iso-profile packages and release mt-0.15.1 after bit of buildiso testing for openrc. lxqt works.

**Comment by udeved** [comment]
budgie should work with elogind, remember, elogind is systemd's logind extracted basically.
Even gnome should sort of starting to work on openrc.

**Comment by oberon2007** [comment]
Sounds good! :+1:

**Comment by udeved** [comment]
Can you make a snapshot from unstable to testing tomorrow?

**Comment by oberon2007** [comment]
Yes, good! :)

**Comment by udeved** [comment]
Just need to put elogind-226.4 release in unstable, and then fire at will.

**Comment by oberon2007** [comment]
New iso-profiles pkgs are now on unstable branch aswell.

**Pull request merged**
